steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/free-161202/cloud-run-test', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/free-161202/cloud-run-test']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'cloud-run-test', '--image', 'gcr.io/free-161202/cloud-run-test', '--region', 'us-central1', '--allow-unauthenticated', '--set-env-vars', 'JAVA_TOOL_OPTIONS=-XX:MaxRAM=256M -XX:MaxRAMPercentage=60']
images:
- gcr.io/cloud-run-test/cloud-run-test
